@startuml
boundary 控制端
entity 服务端
boundary 被控端

== 点对点连接建立 ==
控制端 -> 服务端 : 新建连接A，发送控制请求(被控端会话ID)
服务端 -> 被控端 : 会话连接S，转发请求(被控端会话ID，被控端ChannelId)
被控端 -> 服务端 : 新建连接B，发送控制响应
服务端 -> 控制端 : 经连接A转发控制响应

== 远程控制消息通讯 ==
被控端 -> 服务端 : 经连接B，发送屏幕截图
服务端 -> 控制端 : 经连接A，转发屏幕截图

控制端 -> 服务端 : 经连接A，发送键盘、鼠标事件
服务端 -> 被控端 : 经连接B，转发键盘、鼠标事件

@enduml
