@startditaa
ditta(--no-shadows, scale=0.8)
    /-------------\
    |c1FF         |
    |    Visitor  |
    \-------------/
           |
           v
+-----------------------+
|cYEL     Zuul          |
+-----------------------+
           |
           v
+-----------------------+
|cGRE   consumer        |
+-----------------------+
      |           | 
      v           v
+---------+   +---------+
|Service A|   |Service B|
| provider|   | provider|
|         |   |         |
+---------+   +---------+
@endditaa
